import { createDefaultModule, DefaultModuleContext, inject, LangiumServices, Module, PartialLangiumServices } from 'langium';
import { VideoProviderUiGeneratedModule } from './generated/module';
import { VideoProviderUiValidationRegistry, VideoProviderUiValidator } from './video-provider-ui-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type VideoProviderUiAddedServices = {
    validation: {
        VideoProviderUiValidator: VideoProviderUiValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type VideoProviderUiServices = LangiumServices & VideoProviderUiAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const VideoProviderUiModule: Module<VideoProviderUiServices, PartialLangiumServices & VideoProviderUiAddedServices> = {
    validation: {
        ValidationRegistry: (injector) => new VideoProviderUiValidationRegistry(injector),
        VideoProviderUiValidator: () => new VideoProviderUiValidator()
    }
};

/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createVideoProviderUiServices(context?: DefaultModuleContext): VideoProviderUiServices {
    return inject(
        createDefaultModule(context),
        VideoProviderUiGeneratedModule,
        VideoProviderUiModule
    );
}
